### ISSUE TITLE
vmaf_rc / libvmaf_rc todo

### ISSUE THREAD

**Issue by kylophone** [Netflix/vmaf#499]
`vmaf_rc` and `libvmaf_rc` are mostly feature complete, but there are a few remaining items to address. Chatting with @christosbampis, this is a list we came up with. If you are are aware of other issues or have a question, please add them here.

- [x] Address model naming problems (#486)
- [x] Provide an `vmaf_log()` library logging API.  (#365)
- [x] Add support for both JSON and CSV score logging. (#514, #515)
- [ ] Confidence interval support, and an API that exposes these scores.
- [x] RFC for new library API.  After 1.3.16 is cut, we will broadcast and solicit comments that the next API version (v2.0.0) will be breaking. We will also provide an FFmpeg libavfilter patch at this time as well. 
- [x] Fix all remanent build instructions that haven't been updated since the `meson` updates. (#476)
- [x] API to disable instruction sets like AVX2, etc... (#501)
- [ ] Add import for precomputed score log
