### ISSUE TITLE
libvmaf_rc TODO, towards deprecating libvmaf

### ISSUE THREAD

**Issue by kylophone** [Netflix/vmaf#591]
The following is a list of things to do before `libvmaf` can be fully deprecated and replaced with `libvmaf_rc`:

- [x] Remove `stdatomic.h` dependency from public API. This makes C++ linkage a pain. (#623, #570)
- [x] Provide a comapatibily `compute_vmaf()` API function. (#619, #708)
    - This function will be marked as deprecated and then removed in a future version. This function will be deprecated, unsupported, and should be removable after 1-2 releases.
    - Allows those that rely on libvmaf to not yet be broken, but receive another warning (this time from their compiler).
- [x] Provide a `libvmaf` PSA, as well as `libvmaf` integration examples
- [x] Provide a simple `vmafossexec` => `vmaf_rc` wrapper script (not part of the published package). (#734)
- [x] `s/_rc//g`: Remove `_rc` suffix from library, executable, and headers. (#734)
- [x] update `vmaf_use_feature()` api call to pass feature extractor initialization options. (#592)
- [x] Fix pkg-config mismatch, merge #571
- [ ] `libvmaf_rc` should have no compilation warnings. First fixed and then CI enforced.
- [ ] ABI/API checks in CI. (#590)
- [x] Confirm compilation on non-x86 platforms. (#584, #634, #638, #640, #644)
- [x] Address cross platform published model paths (#324, #724)
- [x] Address output log schema
- [x] VmafConfiguration.cpumask should be a `uint64_t`, can be fixed after libvmaf is deprecated. (#750)
- [x] Address use of `FILE *` in `vmaf_write_output()` (#632, #633)
- [x] Support pooled scores (https://github.com/Netflix/vmaf/issues/591#issuecomment-665338660, #687)

**Comment by dwbuiten** [comment]
> s/_rc//g: Remove _rc suffix from library, executable, and headers.

I assume this includes a corresponding major version SONAME bump?

**Comment by kylophone** [comment]
> > s/_rc//g: Remove _rc suffix from library, executable, and headers.
> 
> I assume this includes a corresponding major version SONAME bump?

Yes.

**Comment by ltrudeau-twoorioles** [comment]
Prior [Netflix tech blog article](https://netflixtechblog.com/vmaf-the-journey-continues-44b51ee9ed12) promoted the use of the harmonic mean. However, this option does not appear to be available with the `vmaf_rc` executable (`--pool harmonic_mean`).

Will this be added or is the harmonic mean not a best practice anymore?

**Comment by kylophone** [comment]
> Prior [Netflix tech blog article](https://netflixtechblog.com/vmaf-the-journey-continues-44b51ee9ed12) promoted the use of the harmonic mean. However, this option does not appear to be available with the `vmaf_rc` executable (`--pool harmonic_mean`).
> 
> Will this be added or is the harmonic mean not a best practice anymore?

Yes it's still important, and yes I'll add it. I have #616 started already, but I'll finish this up and get the pooled scores to the logs.

**Comment by ltrudeau-twoorioles** [comment]
> Yes it's still important, and yes I'll add it. I have #616 started already, I'll finish this up and get the pooled scores to the logs.

Awesome, thanks for the quick reply.

Another minor thing is that `vmaf_rc` output file (xml, json) don't include aggregate scores. Looked into adding it, but the code is designed in such a way that adding this is not straight forward and I don't want to butcher your pretty design.

**Comment by kylophone** [comment]
v2.0.0 is out, please see #751 for v2.0.1 planning.
