### ISSUE TITLE
libvmaf v2.0.1 roadmap

### ISSUE THREAD

**Issue by kylophone** [Netflix/vmaf#751]
While v2.0.0 is still just nascent, we are already planning for `v2.0.1`. `libvmaf` was selected for the metrics implementation to be used for the AOM common test conditions. That set of test conditions is a few weeks from being finalized, and we are planning on releasing `v2.0.1` to coincide with that work.

- [x] `ssim`/`ms_ssim`: Provide `enable_db=true` parameter (#745).
- [x] ~~libvmaf/output: investigate possible aom_ctc specific output format.~~ 
- [x] vmaf: provide `--aom_ctc v1.0` preset. (#785)
- [ ] eliminate the rest of the libvmaf compilation warnings.
- [x] support calculating `VMAF` and `VMAF_NEG` simultaneously. (#785)

This is an incomplete list and it may grow. If there is something you have noticed in the `v2.0.0` release which you believe is applicable, please bring it up if you think it ought to be a part of the `v2.0.1` release.

**Comment by eclipseo** [comment]
Congrats on v2, I'm already enjoying it!

**Comment by vtorri** [comment]
not a feature, but fising all the warning would be nice. I'm compiling libvmaf on Windows, and I have a ton of warnings.

**Comment by ltrudeau-twoorioles** [comment]
Since `libvmaf` was selected as AOM CTC, have you considered adding something similar to 
https://chromium.googlesource.com/webm/contributor-guide
Which appears to be unmaintained.

**Comment by li-zhi** [comment]
Yes. It is in the making. Stay tuned.

**Comment by ltrudeau-twoorioles** [comment]
Any plans to add more NEG models (i.e. 0.6.3neg) or 4k NEG models?

**Comment by li-zhi** [comment]
vmaf_v0.6.1neg.json is meant to be a convenient tool. For other models, it
is better to invoke NEG through feature options. Refer to this section of
our memo for details:
https://docs.google.com/document/d/1dJczEhXO0MZjBSNyKmd3ARiCTdFVMNPBykH4_HMPoyY/edit#

**Comment by ltrudeau-twoorioles** [comment]
I find modifying model feature parameters via the command line a little clunky. Please consider #764. This could remove the need for the NEG variants of the models it could also encapsulate NEG parameters which reduces user error and facilitate updating NEG parameters in the future.

**Comment by slhck** [comment]
This can be closed, right?

**Comment by kylophone** [comment]
> This can be closed, right?

Yes, thanks.
